# Generated by Django 6.1 on 2026-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='media',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
